#!/bin/bash

# Environment
user=$(whoami)
target_dir=/home/$user
omzsh_dir=$target_dir/.oh-my-zsh
plugins_dir=$omzsh_dir/plugins
custom_dir=$omzsh_dir/custom
custom_plugins_dir=$custom_dir/plugins
custom_themes_dir=$custom_dir/themes
fonts_dir=$target_dir/.local/share/fonts

# Oh-My-ZSH
omzsh=(
       $target_dir
       '.oh-my-zsh' 'https://github.com/robbyrussell/oh-my-zsh.git'
      )

# Plugins
plugins=(
         $plugins_dir
         'fzf' 'https://github.com/junegunn/fzf.git'
        )

# Custom plugins
custom_plugins=(
                $custom_plugins_dir
                'zsh-autosuggestions'		'https://github.com/zsh-users/zsh-autosuggestions.git'
                'zsh-syntax-highlighting'	'https://github.com/zsh-users/zsh-syntax-highlighting.git'
                'zsh-completions'		'https://github.com/zsh-users/zsh-completions.git'
                'zsh-history-substring-search'	'https://github.com/zsh-users/zsh-history-substring-search.git'
                'k'				'https://github.com/supercrabtree/k.git'
               )

# Themes
custom_themes=(
               $custom_themes_dir
               'powerlevel10k' 'https://github.com/romkatv/powerlevel10k.git'
              )

# Fonts
fonts=(
       $fonts_dir
       'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf'
       'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/RobotoMono/Regular/complete/Roboto%20Mono%20Nerd%20Font%20Complete.ttf'
       'https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf'
       'https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf'
       'https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf'
       'https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf'
       'https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf'
      )